/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as SubholdingsIndexRouteImport } from './routes/subholdings.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as BudgetMonitoringIndexRouteImport } from './routes/budget-monitoring.index'
import { Route as ApprovalsIndexRouteImport } from './routes/approvals.index'
import { Route as TemplatesNewRouteImport } from './routes/templates.new'
import { Route as SubholdingsSubholdingIdRouteImport } from './routes/subholdings.$subholdingId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as TemplatesTemplateIdEditRouteImport } from './routes/templates.$templateId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubholdingsIndexRoute = SubholdingsIndexRouteImport.update({
  id: '/subholdings/',
  path: '/subholdings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetMonitoringIndexRoute = BudgetMonitoringIndexRouteImport.update({
  id: '/budget-monitoring/',
  path: '/budget-monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsIndexRoute = ApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubholdingsSubholdingIdRoute = SubholdingsSubholdingIdRouteImport.update({
  id: '/subholdings/$subholdingId',
  path: '/subholdings/$subholdingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdEditRoute = TemplatesTemplateIdEditRouteImport.update({
  id: '/templates/$templateId/edit',
  path: '/templates/$templateId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/subholdings/$subholdingId': typeof SubholdingsSubholdingIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/budget-monitoring/': typeof BudgetMonitoringIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subholdings/': typeof SubholdingsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/templates/$templateId/edit': typeof TemplatesTemplateIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/subholdings/$subholdingId': typeof SubholdingsSubholdingIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/approvals': typeof ApprovalsIndexRoute
  '/budget-monitoring': typeof BudgetMonitoringIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/subholdings': typeof SubholdingsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/users': typeof UsersIndexRoute
  '/templates/$templateId/edit': typeof TemplatesTemplateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/subholdings/$subholdingId': typeof SubholdingsSubholdingIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/budget-monitoring/': typeof BudgetMonitoringIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subholdings/': typeof SubholdingsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/templates/$templateId/edit': typeof TemplatesTemplateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/projects/$projectId'
    | '/projects/new'
    | '/subholdings/$subholdingId'
    | '/templates/new'
    | '/approvals/'
    | '/budget-monitoring/'
    | '/projects/'
    | '/reports/'
    | '/settings/'
    | '/subholdings/'
    | '/templates/'
    | '/users/'
    | '/templates/$templateId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/projects/$projectId'
    | '/projects/new'
    | '/subholdings/$subholdingId'
    | '/templates/new'
    | '/approvals'
    | '/budget-monitoring'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/subholdings'
    | '/templates'
    | '/users'
    | '/templates/$templateId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/projects/$projectId'
    | '/projects/new'
    | '/subholdings/$subholdingId'
    | '/templates/new'
    | '/approvals/'
    | '/budget-monitoring/'
    | '/projects/'
    | '/reports/'
    | '/settings/'
    | '/subholdings/'
    | '/templates/'
    | '/users/'
    | '/templates/$templateId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  SubholdingsSubholdingIdRoute: typeof SubholdingsSubholdingIdRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  ApprovalsIndexRoute: typeof ApprovalsIndexRoute
  BudgetMonitoringIndexRoute: typeof BudgetMonitoringIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SubholdingsIndexRoute: typeof SubholdingsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  TemplatesTemplateIdEditRoute: typeof TemplatesTemplateIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subholdings/': {
      id: '/subholdings/'
      path: '/subholdings'
      fullPath: '/subholdings/'
      preLoaderRoute: typeof SubholdingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-monitoring/': {
      id: '/budget-monitoring/'
      path: '/budget-monitoring'
      fullPath: '/budget-monitoring/'
      preLoaderRoute: typeof BudgetMonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/': {
      id: '/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof ApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subholdings/$subholdingId': {
      id: '/subholdings/$subholdingId'
      path: '/subholdings/$subholdingId'
      fullPath: '/subholdings/$subholdingId'
      preLoaderRoute: typeof SubholdingsSubholdingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId/edit': {
      id: '/templates/$templateId/edit'
      path: '/templates/$templateId/edit'
      fullPath: '/templates/$templateId/edit'
      preLoaderRoute: typeof TemplatesTemplateIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  SubholdingsSubholdingIdRoute: SubholdingsSubholdingIdRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  ApprovalsIndexRoute: ApprovalsIndexRoute,
  BudgetMonitoringIndexRoute: BudgetMonitoringIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SubholdingsIndexRoute: SubholdingsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  TemplatesTemplateIdEditRoute: TemplatesTemplateIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
